olx/urls.py
from django.contrib import admin
from django.urls import path
from olx_website import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView
from olx_website.forms import LogginForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('test/', views.test),
    path('', views.homepage, name='home-page'),
    path('item/<pk>/', views.ItemDetailView.as_view(), name='item-detail'),
    path('user/create', views.UserCreateView.as_view(), name='create-user'),
    path('user_login/', views.CustomLoginView.as_view(), name='login'),
    path('add_item/', views.item_create_view, name='add-item'),
    path('delete/<pk>', views.DeleteItem, name='delete-item'),
    path('edit/<pk>', views.EditItemView.as_view(), name='update-item'),
    path('dashboard', views.dashboard, name='dashboard'),
    path('user/logout', views.custom_logout, name='user-logout'),
    path('sport/', views.sport_category, name='sport-category'),
    path('electronics/', views.electronics_category, name='electronics-category'),
    path('clothes/', views.clothes_category, name='clothes-category'),
    path('browse/', views.browse, name='browse'),
    path('rooms/', views.room_list, name='room_list'),
    path('rooms/<int:pk>/', views.room_detail, name='room_detail'),
    path('rooms/create/<int:pk>/', views.new_room, name='create_room'),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

olx_website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import RegexValidator

# Create your models here.

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=9, validators=[RegexValidator(r'^\d{1,9}$')])

class Category(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Condition(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

class Item(models.Model):
    category = models.ForeignKey(Category, related_name='items', on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    image = models.ImageField(upload_to='images', blank=True, null=True)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(blank=True, null=True)
    is_sold = models.BooleanField(default=False)
    condition = models.ForeignKey(Condition, related_name='items', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='items', on_delete=models.CASCADE)

    def __str__(self):
        return self.title

class Room(models.Model):
    item = models.ForeignKey(Item, related_name='rooms', on_delete=models.CASCADE)
    seller = models.ForeignKey(User, related_name='seller_rooms', on_delete=models.CASCADE)
    buyer = models.ForeignKey(User, related_name='buyer_rooms', on_delete=models.CASCADE)

    def __str__(self):
        return f"Room for Item {self.item}"

class Message(models.Model):
    room = models.ForeignKey(Room, related_name='messages', on_delete=models.CASCADE)
    sender = models.ForeignKey(User, related_name='sent_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)
    seen = models.BooleanField(default=False)

    def __str__(self):
        return f"Message from {self.sender} in {self.room}"

olx_website/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db.transaction import atomic
from django.forms import CharField
from olx_website import models
from olx_website.models import Profile

class SignUpForm(UserCreationForm):
    phone_number = CharField(label='Enter your phone number')

    class Meta(UserCreationForm.Meta):
        fields = ['username', 'email', 'password1', 'password2']

    @atomic
    def save(self, commit=True):
        self.instance.is_active = True
        result = super().save(commit)
        phone_number = self.cleaned_data['phone_number']
        profile = Profile(phone_number=phone_number, user=result)
        if commit:
            profile.save()
        return result

class LogginForm(AuthenticationForm):
    username = forms.CharField
    password = forms.CharField


class AddNewItemForm(forms.ModelForm):
    class Meta:
        model = models.Item
        fields = ('title','image', 'condition', 'price', 'description', 'category' )
    #image = forms.ImageField()


class EditItemForm(forms.ModelForm):
    class Meta:
        model = models.Item
        fields = ('title','image', 'condition', 'price', 'description', 'category')


class ChatMessage(forms.ModelForm):
    class Meta:
        model = models.Message
        fields = ('content',)

olx_website/views.py
from django.http import HttpResponse
from django.views.generic import  View, CreateView, UpdateView, DeleteView, FormView
from olx_website import models
from django.urls import reverse_lazy
from django.shortcuts import render, get_object_or_404, redirect

from olx_website import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout
from django.shortcuts import redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.views import LoginView
from olx_website import filters
from .models import Room, Message, Item
from .forms import ChatMessage
# Create your views here.

def test(request):
    return HttpResponse('Siema')

def homepage(request):
    items = models.Item.objects.all().order_by('-created_at')[:14]

    return render(request, 'home_page.html', context={
        'items':items,
    })


class ItemDetailView(View):
    def get(self, request, pk):
        item = get_object_or_404(models.Item, pk=pk)
        return render(request, 'item-detail.html', context={'item': item})


class UserCreateView(CreateView):
    success_url = reverse_lazy('login')
    template_name = 'CreateUser.html'
    form_class = forms.SignUpForm
    model = User


@login_required
def item_create_view(request):
    if request.method == 'POST':
        form = forms.AddNewItemForm(request.POST, request.FILES)
        if form.is_valid():
            item = form.save(commit=False)
            item.created_by = request.user
            print(form.cleaned_data)
            item.save()

            return redirect('item-detail', pk=item.id)
    else:
        form = forms.AddNewItemForm()

    return render(request, 'CreateItem.html', context={
        'form': form,
    })

class EditItemView(LoginRequiredMixin, UpdateView):
    model = models.Item
    form_class = forms.EditItemForm
    template_name = 'edit_item.html'
    success_url = reverse_lazy('item-detail')

    def get_success_url(self):
        return reverse_lazy('item-detail', kwargs={'pk': self.object.pk})

@login_required
def DeleteItem(request, pk):
    item = get_object_or_404(models.Item, pk=pk, created_by=request.user)
    item.delete()

    return redirect('home-page')

@login_required
def dashboard(request):
    items = models.Item.objects.filter(created_by=request.user)
    item_count = items.count()

    return render(request, 'dashboard.html', context={
        'items': items,
        'item_count': item_count
    })


@login_required
def custom_logout(request):
    logout(request)

    return redirect('home-page')


class CustomLoginView(LoginView):
    template_name = 'user_login.html'
    authentication_form = AuthenticationForm

    def get_success_url(self):
        return reverse_lazy('home-page')


def sport_category(request):
    items = models.Item.objects.filter(category__name='Sport')

    return render(request, 'sport_category.html', context={
        'items': items,
    })

def clothes_category(request):
    items = models.Item.objects.filter(category__name='Clothes')

    return render(request, 'clothes_category.html', context={
        'items': items,
    })

def electronics_category(request):
    items = models.Item.objects.filter(category__name='Electronics')

    return render(request, 'electronics_category.html', context={
        'items': items,
    })

def browse(request):
    items = models.Item.objects.all()

    myFilter = filters.OrderFilters(request.GET, queryset=items)
    items = myFilter.qs

    if 'reset' in request.GET:
        myFilter = filters.OrderFilters(queryset=items)
        items = myFilter.qs

    return render(request, 'browse.html', context={
        'items': items,
        'myFilter': myFilter,
    })

@login_required
def new_room(request, pk):
    item = get_object_or_404(Item, pk=pk)

    room = Room.objects.filter(item=item, seller=item.created_by, buyer=request.user).first()
    if room:
        return redirect('room_detail', pk=room.pk)

    if request.method == 'POST':
        form = forms.ChatMessage(request.POST)

        if form.is_valid():
            room = Room.objects.create(item=item, seller=item.created_by, buyer=request.user)
            room.save()

            message = form.save(commit=False)
            message.room = room
            message.sender = request.user
            message.save()

            return redirect('room_detail', pk=room.pk)
    else:
        form = forms.ChatMessage()

    return render(request, 'new.html', context=
    {'form': form})

def room_list(request):
    seller_rooms = Room.objects.filter(seller=request.user)
    buyer_rooms = Room.objects.filter(buyer=request.user)

    return render(request, 'room_list.html', context=
    {'seller_rooms': seller_rooms, 'buyer_rooms': buyer_rooms})

@login_required
def room_detail(request, pk):
    room = get_object_or_404(Room, pk=pk)

    if request.method == 'POST':
        form = forms.ChatMessage(request.POST)

        if form.is_valid():
            message = form.save(commit=False)
            message.room = room
            message.sender = request.user
            message.save()

            return redirect('room_detail', pk=pk)
    else:
        form = forms.ChatMessage()

    messages = Message.objects.filter(room=room)
    return render(request, 'room_detail.html', context=
    {'messages': messages, 'form': form})

olx_website/templates/CreateItem.html
{% extends 'base.html' %}
{% block title %} Add new item {% endblock %}
{% block content %}
<div class="signup-form">
    <h1 class="signup-title">Add new item</h1>
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}

        {{form.non_field_errors}}
        <div class="form-group">
            <label class="form-label">Title</label><br>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label class="form-label">Category</label><br>
            {{ form.category }}
        </div>
        <div class="form-group">
            <label class="form-label">Image</label><br>
            {{ form.image}}
        </div>
        <div class="form-group">
            <label class="form-label">Price</label><br>
            {{ form.price}}
        </div>
        <div class="form-group">
            <label class="form-label">Description</label><br>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label class="form-label">Condition </label><br>
            {{ form.condition  }}
        </div>


        {% if form.errors or form.non_field_errors %}
        <div class="error-messages">
            {% for field in form %}
                {{ field.error }}
            {% endfor %}
        </div>
        {% endif %}

        <button class="signup-button">Submit</button>
    </form>
</div>
{% endblock %}

olx_website/templates/CreateUser.html
{% extends 'base.html' %}
{% block title %} Sign up {% endblock %}
{% block content %}
<div class="signup-form">
    <h1 class="signup-title">Sign Up</h1>
    <form method="post">
        {% csrf_token %}

        {{form.non_field_errors}}
        <div class="form-group">
            <label class="form-label">Username</label><br>
            {{ form.username }}
        </div>
        <div class="form-group">
            <label class="form-label">Password</label><br>
            {{ form.password1 }}
        </div>
        <div class="form-group">
            <label class="form-label">Repeat password</label><br>
            {{ form.password2 }}
        </div>
        <div class="form-group">
            <label class="form-label">E-mail</label><br>
            {{ form.email }}
        </div>
        <div class="form-group">
            <label class="form-label">Phone number</label><br>
            {{ form.phone_number }}
        </div>

        {% if form.errors or form.non_field_errors %}
        <div class="error-messages">
            {% for field in form %}
                {{ field.error }}
            {% endfor %}
        </div>
        {% endif %}

        <button class="signup-button">Submit</button>
    </form>
</div>
{% endblock %}

olx_website/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %} | OLX</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'style.css'%}">
</head>
<body>
<header class="nav_bar">
  <div class="logo-container">
    <a href="/" class="logo">Niby OLX ( ͡° ͜ʖ ͡°) </a>
    <div class="discord-dropdown">
      <label class="discord-dropdown-trigger">Browse categories ▼</label>
      <ul class="discord-dropdown-menu">
        <li><a href="{% url 'clothes-category' %}">Clothes</a></li>
        <li><a href="{% url 'electronics-category' %}">Electronics</a></li>
        <li><a href="{% url 'sport-category' %}">Sport</a></li>
      </ul>
    </div>
  </div>
  <div class="nav_links">
    {% if request.user.is_authenticated %}
    <div class="menu_links">
      <a href="{% url 'add-item' %}" class="nav_link">Add item</a>
      <a href="{% url 'browse' %}" class="nav_link">Browse</a>
      <a href="{% url 'dashboard' %}" class="cta_button-dashboard">Your Items</a>
        <a href="{% url 'room_list' %}" class="cta_button">Conversations</a>
      <a href="{% url 'user-logout' %}" class="cta_button">Logout</a>
    </div>
    {% else %}
    <div class="cta_buttons">
      <a href="{% url 'login' %}" class="cta_button">Log in</a>
      <a href="{% url 'create-user' %}" class="cta_button">Sign Up</a>
    </div>
    {% endif %}
  </div>
</header>
{% block content %}
{% endblock %}
<footer class="footer">
    <div class="social_links">
        <a href="#" class="social_link">Facebook</a>
        <a href="#" class="social_link">Instagram</a>
        <a href="#" class="social_link">Twitter</a>
    </div>
    <div class="footer_links">
        <a href="#" class="footer_link">About</a>
        <a href="#" class="footer_link">Contact & Support</a>
        <a href="#" class="footer_link">Terms of use</a>
        <a href="#" class="footer_link">Privacy policy</a>
    </div>
</footer>
</body>
</html>

olx_website/templates/browse.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Homepage {% endblock %}
{% block content %}

<div class="item-container">
    <h1> Advance Item Search </h1>

    {% csrf_token %}
<form method="get">
  <div class="filter-section">
    <h3>Filters</h3>
    <div class="filter-group">
      <div class="row">
        <div class="filter-field">
          <label for="id_title">Title:</label>
          {{ myFilter.form.title }}
        </div>
        <div class="filter-field">
          <label for="id_category">Category:</label>
          {{ myFilter.form.category }}
        </div>
      </div>
      <div class="row">
          <div class="filter-field">
          <label for="id_start_date">Start Date:</label>
          {{ myFilter.form.start_date }}
        </div>
        <div class="filter-field">
          <label for="id_end_date">End Date:</label>
          {{ myFilter.form.end_date }}
        </div>
      </div>
      <div class="row">
        <div class="filter-field">
          <label for="id_min_price">Min Price:</label>
          {{ myFilter.form.min_price }}
        </div>
        <div class="filter-field">
          <label for="id_max_price">Max Price:</label>
          {{ myFilter.form.max_price }}
        </div>
      </div>
    </div>
    <div class="filter-group">
      <button type="submit">Apply Filters</button>
      <button type="submit" name="reset" value="true">Reset</button>
    </div>
  </div>
</form>

    <div class="item-list">
        {% for item in items %}
        <div class="item">
            <a href="{% url 'item-detail' item.id %}">
                <div class="item-image">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" class="item-img">
                    {% else %}
                        <img src="{% static 'images/default_image.jpg' %}" class="item-img" alt="Domyślne zdjęcie">
                    {% endif %}
                </div>
                <div class="item-details">
                    <h2 class="item-title">{{ item.title }}</h2>
                    <p class="item-price">Price: {{ item.price }} $</p>
                </div>
            </a>
        </div>
        {% endfor %}
</div>
{% endblock %}

olx_website/templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Dashboard {% endblock %}
{% block content %}
<div class="item-container">
    <h1> Your Items </h1>
    <h1> Currently you have {{item_count}} listed items</h1>

    <div class="item-list">
        {% for item in items %}
        <div class="item">
            <a href="{% url 'item-detail' item.id %}">
                <div class="item-image">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" class="item-img">
                    {% else %}
                        <img src="{% static 'images/default_image.jpg' %}" class="item-img" alt="Domyślne zdjęcie">
                    {% endif %}
                </div>
                <div class="item-details">
                    <h2 class="item-title">{{ item.title }}</h2>
                    <p class="item-price">Price: {{ item.price }} $</p>
                </div>
            </a>
        </div>
        {% endfor %}
</div>
{% endblock %}

olx_website/templates/edit_item.html
{% extends 'base.html' %}
{% block title %} Add new item {% endblock %}
{% block content %}
<div class="signup-form">
    <h1 class="signup-title">Edit Item</h1>
    <form method="post" enctype='multipart/form-data'>
        {% csrf_token %}

        {{form.non_field_errors}}
        <div class="form-group">
            <label class="form-label">Title</label><br>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label class="form-label">Category</label><br>
            {{ form.category }}
        </div>
        <div class="form-group">
            <label class="form-label">Image</label><br>
            {{ form.image}}
        </div>
        <div class="form-group">
            <label class="form-label">Price</label><br>
            {{ form.price}}
        </div>
        <div class="form-group">
            <label class="form-label">Description</label><br>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label class="form-label">Condition </label><br>
            {{ form.condition  }}
        </div>


        {% if form.errors or form.non_field_errors %}
        <div class="error-messages">
            {% for field in form %}
                {{ field.error }}
            {% endfor %}
        </div>
        {% endif %}

        <button class="signup-button">Submit</button>
    </form>
</div>
{% endblock %}

olx_website/templates/electronics_category.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Dashboard {% endblock %}
{% block content %}
<div class="item-container">
    <h1> Electronics Items </h1>

    <div class="item-list">
        {% for item in items %}
        <div class="item">
            <a href="{% url 'item-detail' item.id %}">
                <div class="item-image">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" class="item-img">
                    {% else %}
                        <img src="{% static 'images/default_image.jpg' %}" class="item-img" alt="Domyślne zdjęcie">
                    {% endif %}
                </div>
                <div class="item-details">
                    <h2 class="item-title">{{ item.title }}</h2>
                    <p class="item-price">Price: {{ item.price }} $</p>
                </div>
            </a>
        </div>
        {% endfor %}
</div>
{% endblock %}

olx_website/templates/item-detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{item.title}} {% endblock %}
{% block content %}
<div class="item-detail-view-container">
  <h1 class="item-detail-title">{{ item.title }}</h1>
  <div class="item-detail-img-container">
    {% if item.image %}
    <img src="{{ item.image.url }}" class="item-detail-img">
    {% else %}
    <img src="{% static 'images/default_image.jpg' %}" class="item-detail-img" alt="Domyślne zdjęcie">
    {% endif %}
  </div>
  <div>
    <h2 class="item-detail-price">Price: {{ item.price}} $</h2>
    <h3 class="item-detail-condition">Item condition: {{ item.condition }}</h3>
    <p class="item-detail-created_by">Item category: {{ item.category }}</p>
    <h4 class="item-detail-description-header">Item description:</h4>
    <p class="item-detail-description">{{ item.description }}</p>
    <p class="item-detail-created_by">Listing created by: {{ item.created_by }}</p>
    <p class="item-detail-created_at">Listing created at: {{ item.created_at }}</p>
  </div>
  <div class="item-detail-cta_buttons">
    {% if request.user == item.created_by %}
    <a href="{% url 'delete-item' item.id %}" class="item-detail-cta_button">Delete</a>
    <a href="{% url 'update-item' item.id %}" class="item-detail-cta_button">Edit</a>
    {% else %}
    {% if request.user.is_authenticated %}
    <a href="{% url 'create_room' pk=item.id %}" class="item-detail-cta_button">Contact Seller</a>
    {% endif %}
    {% endif %}
  </div>
</div>
{% endblock %}

olx_website/templates/logout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="post">
  {% csrf_token %}
  <p>Czy na pewno chcesz się wylogować?</p>
  <button type="submit">Wyloguj</button>
</form>
</body>
</html>

olx_website/templates/new.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Start Conversation {% endblock %}
{% block content %}
<h1>New conversation</h1>
<div class="new_room">
<form method="post" action=".">
    {% csrf_token %}

    <div class="new-room-form">
        {{ form.content }}
        <div class="new-room-btn-container">
            <button class="new-room-send-btn">Send</button>
        </div>
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="new-room-errors">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
</form>
</div>
{% endblock %}

olx_website/templates/room_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Conversation Room for {{ messages.room.item.title }}{% endblock %}
{% block content %}
  <h1 class="conversation-title">Conversation</h1>

  <div class="room-detail-container">
    <div class="room-messages">
      {% for message in messages %}
        <div class="message {% if message.sender == request.user %}sent{% else %}received{% endif %}">
          <p>{{ message.content }}</p>
          <p class="message-sender">From: {{ message.sender }}</p>
          <p class="message-timestamp">Timestamp: {{ message.timestamp }}</p>
        </div>
      {% empty %}
        <p>No messages available.</p>
      {% endfor %}
    </div>

   <h2>New Message</h2>
<div class="new_room">
<form method="post" action=".">
    {% csrf_token %}

    <div class="new-room-form">
        {{ form.content }}
        <div class="new-room-btn-container">
            <button class="new-room-send-btn">Send</button>
        </div>
    </div>

    {% if form.errors or form.non_field_errors %}
        <div class="new-room-errors">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
</form>
    </div>
  </div>
{% endblock %}

olx_website/templates/room_list.html
{% extends 'base.html' %}
{% load static %}
{% block title %} My Conversations {% endblock %}
{% block content %}
<h1 class="rooms-title">My Rooms</h1>
<div class="new_room">

<h2 class="conversations-title">Seller Conversations:</h2>
{% for room in seller_rooms %}
  <div class="room">
    <div class="inside-room">
      <p class="room-info">Item: {{ room.item }}</p>
      <p class="room-info">Buyer: {{ room.buyer }}</p>
    </div>
    <div class="inside-room">
      <img src="{{ room.item.image.url }}" alt="Item Image" class="room-image">
    </div>
    <div class="inside-room">
      <p><a href="{% url 'room_detail' room.id %}" class="room-link">Go to Room</a></p>
    </div>
  </div>
{% empty %}
  <p>No seller rooms available.</p>
{% endfor %}

<h2 class="conversations-title">Buyer Conversations:</h2>
{% for room in buyer_rooms %}
  <div class="room">
    <div class="inside-room">
      <p class="room-info">Item: {{ room.item }}</p>
      <p class="room-info">Seller: {{ room.seller }}</p>
    </div>
    <div class="inside-room">
      <img src="{{ room.item.image.url }}" alt="Item Image" class="room-image">
    </div>
    <div class="inside-room">
      <p><a href="{% url 'room_detail' room.id %}" class="room-link">Go to Room</a></p>
    </div>
  </div>
{% empty %}
  <p>No buyer rooms available.</p>
{% endfor %}

</div>

{% endblock %}

olx_website/templates/sport_category.html
{% extends 'base.html' %}
{% load static %}
{% block title %} Dashboard {% endblock %}
{% block content %}
<div class="item-container">
    <h1> Sport Items </h1>

    <div class="item-list">
        {% for item in items %}
        <div class="item">
            <a href="{% url 'item-detail' item.id %}">
                <div class="item-image">
                    {% if item.image %}
                    <img src="{{ item.image.url }}" class="item-img">
                    {% else %}
                        <img src="{% static 'images/default_image.jpg' %}" class="item-img" alt="Domyślne zdjęcie">
                    {% endif %}
                </div>
                <div class="item-details">
                    <h2 class="item-title">{{ item.title }}</h2>
                    <p class="item-price">Price: {{ item.price }} $</p>
                </div>
            </a>
        </div>
        {% endfor %}
</div>
{% endblock %}

olx_website/templates/user_login.html
{% extends 'base.html' %}
{% block title %} Sign up {% endblock %}
{% block content %}
<div class="signup-form">
    <h1 class="signup-title">Log in</h1>
    <form method="post">
        {% csrf_token %}

        {{form.non_field_errors}}
        <div class="form-group2">
            <label class="form-label">Username</label><br>
            {{ form.username }}
        </div>
        <div class="form-group2">
            <label class="form-label">Password</label><br>
            {{ form.password}}
        </div>


        {% if form.errors or form.non_field_errors %}
        <div class="error-messages">
            {% for field in form %}
                {{ field.error }}
            {% endfor %}
        </div>
        {% endif %}

        <button class="signup-button">Submit</button>
    </form>
</div>
{% endblock %}